Add priority to Applied controls
intuitem/ciso-assistant-community pull request #1059
Opened 2024-11-19 00:18 UTC by melinoix

Added the field priority on applied controls with colored flags on the detailView and the modeltable.

2024-11-19 03:52 UTC, ab-smith commented on backend/core/views.py
> +        "priority" "effort",
,

2024-11-19 13:38 UTC, nas-tabchiche requested changes
`priority` has to be a number.
django's [PositiveSmallIntegerField](https://docs.djangoproject.com/en/5.1/ref/models/fields/#positivesmallintegerfield) seems like a good pick for this.

2024-11-19 13:38 UTC, nas-tabchiche commented on backend/core/models.py
> +    )
This is not compliant with the specs. Priority has to be an integer, "P1", "P2"... are only labels.

2024-11-20 22:06 UTC, eric-intuitem commented
When I edit an applied control, the priority is not kept, it is set to --.

2024-11-20 22:07 UTC, eric-intuitem requested changes
Priority shall be correctly initialised when entering the edit page.

2024-11-21 17:45 UTC, ab-smith approved these changes
functional ok

2024-11-21 17:47 UTC, merged