Return an error message when an admin try to delete the only admin account
intuitem/ciso-assistant-community pull request #192
Opened 2024-04-02 20:34 UTC by monsieurswag

I removed import { fail } from 'assert'; in "frontend/src/routes/(app)/users/[id=uuid]/edit/+page.server.ts", it seems like it was an error surely from someone who auto-imported the wrong fail function in a previous commit.

According to this Mixin definition the "name" field isn't unique which means there may multiple UserGroup object with the same name :

```
class NameDescriptionMixin(AbstractBaseModel):
    name = models.CharField(max_length=200, verbose_name=_("Name"), unique=False)
```

I am not sure having 2 user groups with the exact same name should be authorized by the application, is this normal ?
If some evil user could create a user group with the same name as the admin group and bypass some permission checks.
To address this potential issue in my code i always added builtin=True when fetching the admin group since builtin objects are meant to be immutable.

2024-04-02 23:58 UTC, eric-intuitem commented
Indeed, once groups will be user-defined, we'll need to add     fields_to_check = ["name"]

2024-04-03 00:00 UTC, eric-intuitem requested changes
Missing translation

2024-04-03 09:33 UTC, monsieurswag commented
Done

2024-04-03 16:11 UTC, Mohamed-Hacene commented on backend/iam/models.py
> +from typing import Any, List, Self, Tuple, Self
Remove `Self` duplication

2024-04-03 16:11 UTC, Mohamed-Hacene commented on backend/core/views.py
> +            admin_group = UserGroup.get_admin_group()
It would be better to get admin group directly without using a method for it

2024-04-03 16:15 UTC, monsieurswag commented
Remove builtin and user_groups__builtin

2024-04-05 08:45 UTC, Mohamed-Hacene approved these changes
0k

2024-04-05 09:20 UTC, eric-intuitem approved these changes
LGTM

2024-04-05 09:20 UTC, merged