The Threat detail view now display the library name instead of its id
intuitem/ciso-assistant-community pull request #197
Opened 2024-04-03 13:48 UTC by monsieurswag

2024-04-03 15:21 UTC, nas-tabchiche requested changes
Use `FieldsRelatedField` with the fields `name` and `urn` to avoid fetching unused data when fetching threats

2024-04-03 15:21 UTC, nas-tabchiche commented on backend/core/serializers.py
> +    library = LibraryReadSerializer()
Serializing the entirety of each threat's library is overkill, as only their names and urns are needed.

2024-04-03 16:16 UTC, eric-intuitem approved these changes
LGTM

2024-04-05 09:11 UTC, eric-intuitem requested changes
Not working for reference controls

2024-04-05 09:14 UTC, eric-intuitem approved these changes
LGTM now

2024-04-05 10:41 UTC, eric-intuitem approved these changes
LGTM

2024-04-05 10:43 UTC, eric-intuitem commented
Nassim's request has been addressed.

2024-04-05 10:43 UTC, merged