Update README to include backend authentication-related environment v…
intuitem/ciso-assistant-community pull request #443
Opened 2024-05-16 18:38 UTC by nas-tabchiche

…ariables

2024-05-16 18:40 UTC, ab-smith requested changes
The md formatter breaks the call-out

2024-05-16 18:40 UTC, ab-smith commented on README.md
> +> [!NOTE] > `*` These frameworks require an extra manual step of getting the latest Excel sheet through their website as their license prevent direct usage.
The md formatter breaks the call-out

2024-05-16 21:22 UTC, eric-intuitem approved these changes
LGTM

2024-05-17 21:51 UTC, nas-tabchiche commented on README.md
> +> [!NOTE] > `*` These frameworks require an extra manual step of getting the latest Excel sheet through their website as their license prevent direct usage.
should be good now

2024-05-18 00:05 UTC, ab-smith approved these changes

2024-05-18 00:05 UTC, merged