Changing domain manager permissions
intuitem/ciso-assistant-community pull request #858
Opened 2024-09-23 08:17 UTC by melinoix

Domain manager permissions are changed to allow to create reference control inside his domain/sub-domains

2024-09-23 18:32 UTC, nas-tabchiche requested changes
### To do

Change `{view,change,delete}_appliedcontrol` to `{view,change,delete}_referencecontrol`.

2024-09-23 18:32 UTC, nas-tabchiche commented on backend/core/startup.py
The task's subject was to allow the creation, edition and deletion of a `ReferenceControl`, not `AppliedControl`. Furthermore, `view_appliedcontrol` is present twice in the list. Once on [line 132](https://github.com/intuitem/ciso-assistant-community/blob/a379d48dd178d6af9203da86143a917a72f2bae0/backend/core/startup.py#L132) and once on line 179.
For the first point, after reading **my own** comment under the ticket, I realized I wrote `_appliedcontrol`. My mistake. Still, a domain manager has no business managing applied controls 😉

2024-09-30 06:20 UTC, eric-intuitem commented on backend/core/startup.py
Let's keep it simple: a domain manager can do anything in its domain.

2024-10-03 13:26 UTC, nas-tabchiche commented
Closing this in favor of #893

2024-10-03 13:26 UTC, closed without merging