Add applied control duplication
intuitem/ciso-assistant-community pull request #940
Opened 2024-10-15 08:27 UTC by monsieurswag

2024-10-15 09:16 UTC, Mohamed-Hacene requested changes
- [ ] Use a slot for duplication button inside the DetailView
- [ ] Add a checkbox to bring the evidence if needed

2024-10-16 14:24 UTC, monsieurswag commented
We don't need a to use a slot now, the code can be easily adapted to add duplication for other objects.
The checkbox to bring the evidences has been added, check its behavior in the backend (some evidences are just linked while other are duplicated depending on their folder)

2024-11-18 11:03 UTC, nas-tabchiche commented on backend/core/views.py
> +        return Response({"results": "applied control duplicated"})
Let's return the actual controls as JSON

2024-11-18 11:23 UTC, Mohamed-Hacene submitted a review, later dismissed
- Field `has_evidence` (and `eta_missed` by the way) should be excluded. We cannot add evidence from the applied control anymore.
![image](https://github.com/user-attachments/assets/51695821-2e5c-40d6-b9a0-9d6c239d61c8)
- The checkbox has unrelated text with this PR
![image](https://github.com/user-attachments/assets/86a55557-545d-4895-9afc-0f8317b668f2)

2024-12-03 13:11 UTC, ab-smith commented
Pensez au squash au moment du merge

2024-12-04 17:48 UTC, eric-intuitem approved these changes
LGTM

2024-12-04 19:14 UTC, eric-intuitem approved these changes
LGTM

2024-12-04 19:15 UTC, merged